# Check with
# yamllint CI.yaml | grep syntax

on:
  push:
    branches: [ main, eh-1-alpha]
  pull_request:
  schedule:
    - cron: 0 1 * * 1

name: Build

env:
  CARGO_TERM_COLOR: always

jobs:

# ON THIS BRANCH ONLY STM32F4XX TESTING FOR eh-1-alpha IS DONE. REMOVE COMMENT LINES BEFOR MERGING !!!

# The first job is only with dev-testing on bluepill and discovery-stm32f303. It goes by example so they
# are all attempted. The job does not stop at the first example to fail. This is nice for 
# identifying problems in the examples, but is slow because of rebuild for each example.
# (It would be faster if I could get caching to work.)
# The 2nd job runs a matrix of 2 (previously 4) stratagies x 14 boards. 
# For each matrix point all examples are run with a single build. This is faster but
# terminates on the first example failure so examples that are known to fail are omitted.

# The strategies are release-testing, driver-testing, hal-testing, and dev-testing.
# The differnce is set in the Cargo.toml file in the manifest directories.
# The release-testing uses release versions of both the driver crate and the HAL crate.
# disabled: The driver-testing  uses the git versions of the driver crate and the release version of the HAL crate.
# disabled: The   hal-testing   uses the release versions of the driver crate and the git version of the HAL crate.
# The   dev-testing   uses git versions of both the driver crate and the HAL crate.

#################################################################################################

# examples:
#   name: eg
  examples:
    name: eh-1
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        brd: [blackpill-stm32f411]  
        # brd: [bluepill, discovery-stm32f303]


        eg:  [blink3,                  blink_impl,                   blink,     dht,   
              echo_by_char,            echo_string,                      gps_rw,        
              oled_gps,                serial_char,                      serial_string,        
              temperature,             text_i2c,                         battery_monitor_ads1015,
              ad9833-midi-player,      ads1015-adc-display,              at24c256-eeprom,   
              bmi160-imu-display,      digi_pot,                         oled_dht,
              ccs811-gas-voc-display,  ccs811-gas-voc-hdc2080-display,   
              ds1307-rtc,              hdc2080-temp-humidity-display,    iaq-core-c-gas-voc-display, 
              isl29125-color-display,  max17043-battery-monitor-display, max30102-heart-usart, 
              mcp7940n-rtc-display,    mlx90614-temperature-display,     mlx90615-temperature-display, 
              mma8452-accel-display,   opt3001-als-display,              pca9685-pwm-rgb-led-servos, 
              si4703-fm-radio-display, si4703-fm-radio,                  tcs34725-color-display,
              tmp006-ir-temp-display,  tmp102-temp-display,              
              veml6030-als-display,    veml6070-uv-display,              veml6075-uv-display,     
              iaq-core-c-gas-voc-usart-logger,   ccs811-gas-voc-usart-logger,
              lora_spi_send,           lora_spi_receive,                 lora_spi_gps,
              blink_rtic,              schedule,                         resource-user-struct,
              dht_rtic,                ccs811-co2-voc,                   battery_monitor_ads1015_rtic,
              display_stuff_rtic,
             ]


#       #NB sections in brd above must be one-to-one with brd: below or matrix is messed up
#       # (somewhat trivial here because there is only bluepill)
        include:
#          - brd: "bluepill"
#            mcu:  stm32f103
#            hal: "stm32f1xx"
#            trg: "thumbv7m-none-eabi"
#          - brd: "discovery-stm32f303"
#            mcu:  stm32f303xc
#            hal: "stm32f3xx"
#            trg: "thumbv7em-none-eabihf"
           - brd: "blackpill-stm32f411"
             mcu:  stm32f411
             hal: "stm32f4xx"
             trg: "thumbv7em-none-eabihf"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.trg }}
    
      - name: Configure caching 
        uses: actions/cache@v2
        with:
          key: ${{ matrix.brd }}
          path: |
            ${{ env.HOME }}/.cargo
            target

      - name: tree
        #--manifest-path to find Caro.toml.      
        uses: actions-rs/cargo@v1 
        with:
          command: tree
          args:  --manifest-path dev-testing/Cargo.toml 

      - name: tree -i embedded-hal:0.2.7
        uses: actions-rs/cargo@v1 
        with:
          command: tree
          args:  --manifest-path dev-testing/Cargo.toml  -i embedded-hal:0.2.7

      - name: tree -i embedded-hal:1.0.0-alpha.7
        uses: actions-rs/cargo@v1 
        with:
          command: tree
          args:  --manifest-path dev-testing/Cargo.toml  -i embedded-hal:1.0.0-alpha.7

      - name: Build
        uses: actions-rs/cargo@v1 
        with:
          command: build
          args:  --manifest-path dev-testing/Cargo.toml --no-default-features --release --target ${{ matrix.trg }} --features ${{ matrix.hal }},${{ matrix.mcu }}
          use-cross: true

      - name: Build example 
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --manifest-path  dev-testing/Cargo.toml  --release --target ${{ matrix.trg }} --features ${{ matrix.hal }},${{ matrix.mcu }} --example ${{ matrix.eg }}
          use-cross: true

